### ISSUE TITLE
报错： ValueError: Could not find trained model in model_dir: /tmp/tmpxlwy5mwx.

### ISSUE THREAD

**Issue by bound2020** [terrifyzhao/bert-utils#3]
我直接跑的extract_feature.py，报了这个错之后，就一直卡着不动了

**Comment by bound2020** [comment]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "extract_feature.py", line 85, in predict_from_queue
    for i in prediction:
  File "/usr/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 480, in predict
    self._model_dir))
ValueError: Could not find trained model in model_dir: /tmp/tmpxlwy5mwx.

**Comment by terrifyzhao** [comment]
I have fixed the bug, please pull the code again

**Comment by bound2020** [comment]
Verified.
