### ISSUE TITLE
按说明运行文本分类，最后提示 BertSim对象没有test方法

### ISSUE THREAD

**Issue by yaleimeng** [terrifyzhao/bert-utils#39]
训练和评估都完成了。
INFO:tensorflow:***** Eval results *****
INFO:tensorflow:  eval_accuracy = 0.5
INFO:tensorflow:  eval_auc = 0.5
INFO:tensorflow:  eval_loss = 0.6931482
INFO:tensorflow:  global_step = 7812
INFO:tensorflow:  loss = 0.6931507
最后提示：
Traceback (most recent call last):
  File "fenlei.py", line 15, in <module>
    bs.test()
AttributeError: 'BertSim' object has no attribute 'test'
我看了一下similarity.py源码，确实没有这个方法。请作者有空时进行解答或者修复，谢谢。

**Comment by aiainui** [comment]
大佬把predict写成test了，改一下就好了。

> 训练和评估都完成了。
> INFO:tensorflow:***** Eval results *****
> INFO:tensorflow: eval_accuracy = 0.5
> INFO:tensorflow: eval_auc = 0.5
> INFO:tensorflow: eval_loss = 0.6931482
> INFO:tensorflow: global_step = 7812
> INFO:tensorflow: loss = 0.6931507
> 最后提示：
> Traceback (most recent call last):
> File "fenlei.py", line 15, in 
> bs.test()
> AttributeError: 'BertSim' object has no attribute 'test'
> 我看了一下similarity.py源码，确实没有这个方法。请作者有空时进行解答或者修复，谢谢。

@yaleimeng

**Comment by yaleimeng** [comment]
@aiainui  你对这块研究多吗？
想做简单的文本分类（类似新闻主题分类）应该怎样改造？
我替换了一下SimProcesser，返回的label列表就是新闻类别，但是运行中又提示predict值只能是[0,1]。完全搞不明白哪里还有问题了。
而且直接执行原始代码的话，基本跟瞎猜是一样的。二分类只能猜中0.5，预测概率基本也都是0.49多，感觉项目中存在重大bug。

**Comment by yaleimeng** [comment]
我在博览众码的基础上，终于解决了工业场景实用化的问题。使得模型预测的结果更直观、可追溯。让使用Bert做文本分类不再困难。
现已开源了代码库[TextClassify_with_BERT](https://github.com/yaleimeng/TextClassify_with_BERT)，还在持续完善中。欢迎大家跟我沟通交流~
