### ISSUE TITLE
when run BertSim

### ISSUE THREAD

**Issue by sunjinguo** [terrifyzhao/bert-utils#6]
hello, I have a question when I run the text classify.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:*** Features ***
INFO:tensorflow:  name = input_ids, shape = (128, 32)
INFO:tensorflow:  name = input_mask, shape = (128, 32)
INFO:tensorflow:  name = label_ids, shape = (128,)
INFO:tensorflow:  name = segment_ids, shape = (128, 32)
Traceback (most recent call last):
  File "bert_train.py", line 10, in <module>
    bs.train()
  File "/data0/home/jinguo3/workspace/jinguo3/bert/bert_demo/bert-utils/similarity.py", line 627, in train
    estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
  File "/data0/home/jinguo3/anaconda2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/data0/home/jinguo3/anaconda2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/data0/home/jinguo3/anaconda2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1237, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/data0/home/jinguo3/anaconda2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/data0/home/jinguo3/workspace/jinguo3/bert/bert_demo/bert-utils/similarity.py", line 203, in model_fn
    num_labels, use_one_hot_embeddings)
TypeError: unbound method create_model() must be called with BertSim instance as first argument (got BertConfig instance instead)
 Thanks

**Comment by terrifyzhao** [comment]
你没有实例化BertSim 对象
